// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cFV4LX4HeIXh8KDmitnlukn0SeikuXU',
    appId: '1:236461047978:web:320d8a8befde673cb010d3',
    messagingSenderId: '236461047978',
    projectId: 'businessgame-2124146',
    authDomain: 'businessgame-2124146.firebaseapp.com',
    storageBucket: 'businessgame-2124146.firebasestorage.app',
    measurementId: 'G-TYELFRQ1D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh1TukwlZrf2vhx_kEa41hXJBzZnSJiEU',
    appId: '1:236461047978:android:3b7a084ceab05b42b010d3',
    messagingSenderId: '236461047978',
    projectId: 'businessgame-2124146',
    storageBucket: 'businessgame-2124146.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7cFV4LX4HeIXh8KDmitnlukn0SeikuXU',
    appId: '1:236461047978:web:c76255e2f4bde258b010d3',
    messagingSenderId: '236461047978',
    projectId: 'businessgame-2124146',
    authDomain: 'businessgame-2124146.firebaseapp.com',
    storageBucket: 'businessgame-2124146.firebasestorage.app',
    measurementId: 'G-575DFQH4VW',
  );

}